version: "3.9"
services:
  app:
    build: ./app
    image: ${DOCKER_REGISTRY}/iktos_test_app
    links:
      - db
    ports:
      - "80:5000"
  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./db/data:/var/lib/mysql-files/